# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nesrd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nesrd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnesrd.proto\x12\x05nesrd\"\x98\x01\n\tFileEvent\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x11\n\tfile_path\x18\x04 \x01(\t\x12\x16\n\x0e\x66ile_extension\x18\x05 \x01(\t\x12\r\n\x05\x62ytes\x18\x06 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x03\"g\n\x0b\x45ventWindow\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_ip\x18\x03 \x01(\t\x12 \n\x06\x65vents\x18\x04 \x03(\x0b\x32\x10.nesrd.FileEvent\"\x9e\x01\n\x0f\x44\x65tectionResult\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x64\x65\x63ision\x18\x03 \x01(\t\x12\x17\n\x0fmitre_technique\x18\x04 \x01(\t\x12\x0e\n\x06reason\x18\x05 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\x12\x12\n\nprocess_id\x18\x07 \x01(\x05\"E\n\tHeartbeat\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_ip\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\":\n\x0cHeartbeatAck\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x32\x86\x01\n\x0cNESRDService\x12>\n\x0cStreamEvents\x12\x12.nesrd.EventWindow\x1a\x16.nesrd.DetectionResult(\x01\x30\x01\x12\x36\n\rSendHeartbeat\x12\x10.nesrd.Heartbeat\x1a\x13.nesrd.HeartbeatAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nesrd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEEVENT']._serialized_start=23
  _globals['_FILEEVENT']._serialized_end=175
  _globals['_EVENTWINDOW']._serialized_start=177
  _globals['_EVENTWINDOW']._serialized_end=280
  _globals['_DETECTIONRESULT']._serialized_start=283
  _globals['_DETECTIONRESULT']._serialized_end=441
  _globals['_HEARTBEAT']._serialized_start=443
  _globals['_HEARTBEAT']._serialized_end=512
  _globals['_HEARTBEATACK']._serialized_start=514
  _globals['_HEARTBEATACK']._serialized_end=572
  _globals['_NESRDSERVICE']._serialized_start=575
  _globals['_NESRDSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
